language: node_js
node_js:
  - "10.14.2"
cache:
  directories:
  - node_modules
script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  target-branch: master
  keep-history: true
  on:
    branch: develop
